#pragma once

static constexpr std::string_view defaultLayout = "[Window][DockSpace Demo]\n"
                                                  "Pos=0,0\n"
                                                  "Size=1280,720\n"
                                                  "Collapsed=0\n"
                                                  "\n"
                                                  "[Window][Debug##Default]\n"
                                                  "Pos=60,60\n"
                                                  "Size=400,400\n"
                                                  "Collapsed=0\n"
                                                  "\n"
                                                  "[Window][Dear ImGui Demo]\n"
                                                  "Pos=372,206\n"
                                                  "Size=899,642\n"
                                                  "Collapsed=0\n"
                                                  "\n"
                                                  "[Window][Dear ImGui Demo/ResizableChild_D5443E47]\n"
                                                  "IsChild=1\n"
                                                  "Size=573,136\n"
                                                  "\n"
                                                  "[Window][Dear ImGui Demo/Red_1D4E05CE]\n"
                                                  "IsChild=1\n"
                                                  "Size=200,100\n"
                                                  "\n"
                                                  "[Window][DeviceList]\n"
                                                  "Pos=0,204\n"
                                                  "Size=366,516\n"
                                                  "Collapsed=0\n"
                                                  "DockId=0x00000003,0\n"
                                                  "\n"
                                                  "[Window][About Dear ImGui]\n"
                                                  "Pos=60,60\n"
                                                  "Size=570,126\n"
                                                  "Collapsed=0\n"
                                                  "\n"
                                                  "[Window][Example: Documents]\n"
                                                  "Pos=154,42\n"
                                                  "Size=621,714\n"
                                                  "Collapsed=0\n"
                                                  "\n"
                                                  "[Window][Delete?]\n"
                                                  "Pos=1124,636\n"
                                                  "Size=311,105\n"
                                                  "Collapsed=0\n"
                                                  "\n"
                                                  "[Window][RSSIPlot]\n"
                                                  "Pos=0,23\n"
                                                  "Size=1280,181\n"
                                                  "Collapsed=0\n"
                                                  "DockId=0x00000001,0\n"
                                                  "\n"
                                                  "[Docking][Data]\n"
                                                  "DockSpace     ID=0x3BC79352 Window=0x4647B76E Pos=0,23 Size=1280,697 Split=Y\n"
                                                  "  DockNode    ID=0x00000001 Parent=0x3BC79352 SizeRef=1280,181 HiddenTabBar=1 Selected=0x2E99C75D\n"
                                                  "  DockNode    ID=0x00000002 Parent=0x3BC79352 SizeRef=1280,518 Split=X Selected=0xE87781F4\n"
                                                  "    DockNode  ID=0x00000003 Parent=0x00000002 SizeRef=366,946 HiddenTabBar=1 Selected=0x1FC2A0E1\n"
                                                  "    DockNode  ID=0x00000004 Parent=0x00000002 SizeRef=1488,946 CentralNode=1 HiddenTabBar=1\n"
                                                  "";